---
- hosts: all
  become: true
  become_method: sudo

  vars:
    mysql_root_pass: pass

  tasks:
    - name: set timezone to Europe/Warsaw
      timezone:
        name: Europe/Warsaw
      tags: config

    - locale_gen:
        name: en_US.UTF-8
        state: absent
      tags: config

    - name: update APT
      apt:
        update_cache: yes

    - name: Install git
      apt:
        name: git
      tags: git

    - name: Set MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_pass | quote}}' vtype='password'
      tags: mysql

    - name: Confirm MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_pass | quote}}' vtype='password'
      tags: mysql

    - name: install mysql
      apt:
        name: mysql-server
      tags: mysql

    - name: create database test
      shell: mysql -u root -p{{ mysql_root_pass }} -e "CREATE DATABASE IF NOT EXISTS test;"

    - name: clone test_db
      shell: git clone https://github.com/dgrochowski/test_db.git /home/vagrant/test_db

    - name: import DB
      shell: cd /home/vagrant/test_db/ && mysql -u root -p{{ mysql_root_pass }} test < employees.sql
