---
- hosts: all
  become: true
  become_method: sudo

  vars:
    mysql_root_pass: pass

  tasks:
    - name: set timezone to Europe/Warsaw
      timezone:
        name: Europe/Warsaw
      tags: config

    - locale_gen:
        name: en_US.UTF-8
        state: absent
      tags: config

    - name: update APT
      apt:
        update_cache: yes

    - name: install git
      apt:
        name: git
      tags: git

    - name: set MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_pass | quote}}' vtype='password'
      tags: mysql

    - name: confirm MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_pass | quote}}' vtype='password'
      tags: mysql

    - name: install mysql
      apt:
        name: "{{ item }}"
        state: installed
      with_items:
       - mysql-server
       - python-mysqldb
       - python-selinux

    - name: clone test_db
      git:
        repo: https://github.com/dgrochowski/test_db.git
        dest: test_db

    # IMPORTANT - ANSIBLE mysql_db IMPORT REQUIRES RELATIVE PATHS FOR THE SOURCE METHOD
    - name: move test_db files
      shell: cp -R test_db/* . && rm -rf test_db

    - name: import DB
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        config_file: no
        state: import
        name: all
        target: employees.sql
